#!/usr/bin/env python3
"""
Emit fig_paramdrift.tex from the real BASELINE drift run.

Source: OpenHydroTwin/deployments/Bioretention_assimilation_MCMC_drift_BASELINE/
        outputs/calibration/posterior_history.jsonl
Truth schedule: Bioretention_truth_drift/config.json -> drift/ksat_drift.csv
  EngSoilKsat = 10 m/day until Excel serial 44166 (2020-11-30),
  ramped to 2 m/day by 44197 (2020-12-31), 2 thereafter.

t_now in the history is an Excel serial date; day 0 here is 2020-01-01
(serial 43831).
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
RUN = os.path.join(
    HERE, '..', '..', '..', 'OpenHydroTwin', 'deployments',
    'Bioretention_assimilation_MCMC_drift_BASELINE',
    'outputs', 'calibration', 'posterior_history.jsonl')
OUT = os.path.join(HERE, 'fig_paramdrift.tex')

EPOCH = 43831.0          # 2020-01-01
ONSET, FULL = 44166.0, 44197.0
PARAM = 'EngineeredSoilKsat'

rows = [json.loads(l) for l in open(RUN) if l.strip()]
i = rows[0]['parameter_names'].index(PARAM)

est, lo, hi = [], [], []
for r in rows:
    d = r['t_now'] - EPOCH
    est.append((d, r['point_estimate'][i]))
    if r.get('p025') and r.get('p975'):
        lo.append((d, r['p025'][i]))
        hi.append((d, r['p975'][i]))

def coords(pts):
    return " ".join("(%.1f,%.4f)" % p for p in pts)

onset, full = ONSET - EPOCH, FULL - EPOCH
xmax = max(p[0] for p in est)

tex = r"""%% GENERATED by make_paramdrift.py -- do not edit by hand.
%% Real output of the BASELINE drift run; truth schedule from the truth deployment.
\documentclass[border=4pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{helvet}
\renewcommand\familydefault{\sfdefault}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepgfplotslibrary{fillbetween}

\definecolor{ohqblue}{HTML}{1F5C8B}
\definecolor{ohqteal}{HTML}{2A9D8F}
\definecolor{ohqrust}{HTML}{E76F51}
\definecolor{ohqgrey}{HTML}{6B7280}

\begin{document}
\begin{tikzpicture}[font=\sffamily]
\begin{axis}[
  width=15cm, height=7.4cm,
  xmin=0, xmax=__XMAX__, ymin=0, ymax=15,
  xlabel={days of operation},
  ylabel={engineered soil $K_{sat}$ (m/day)},
  label style={font=\small, text=ohqgrey},
  tick label style={font=\small, text=ohqgrey},
  axis line style={ohqgrey!60}, tick style={ohqgrey!60},
  grid=major, major grid style={ohqgrey!15},
  xtick={0,90,180,270,360,450,540,630,720},
  legend style={font=\small, draw=ohqgrey!40, at={(0.02,0.04)},
                anchor=south west, fill=white, row sep=1pt},
  legend cell align=left,
]
% 95% credible band
\addplot[name path=lo, draw=none, forget plot] coordinates {__LO__};
\addplot[name path=hi, draw=none, forget plot] coordinates {__HI__};
\addplot[ohqblue!16] fill between[of=lo and hi];
\addlegendentry{95\% credible interval}

% imposed truth
\addplot[ohqrust, line width=1.6pt, dashed] coordinates {
  (0,10) (__ONSET__,10) (__FULL__,2) (__XMAX__,2)};
\addlegendentry{true value, imposed}

% per-cycle estimate
\addplot[ohqblue, line width=1.1pt] coordinates {__EST__};
\addlegendentry{twin's estimate}

\draw[ohqgrey, dashed, line width=0.8pt]
  (axis cs:__ONSET__,0) -- (axis cs:__ONSET__,15);
\node[font=\small, text=ohqgrey, anchor=south east, rotate=90]
  at (axis cs:__ONSET__,0.4) {clogging begins\ \ };
\end{axis}
\end{tikzpicture}
\end{document}
"""
tex = (tex.replace('__XMAX__', '%.0f' % xmax)
          .replace('__ONSET__', '%.0f' % onset)
          .replace('__FULL__', '%.0f' % full)
          .replace('__EST__', coords(est))
          .replace('__LO__', coords(lo))
          .replace('__HI__', coords(hi)))
open(OUT, 'w').write(tex)
print("wrote fig_paramdrift.tex from %d cycles" % len(rows))
