#!/usr/bin/env python3
"""
Regenerate the template montage for the overview deck.

Reads resources/default_templates.list, which is the same list the GUI's
"Add plugin" menu is built from, so the slide always shows exactly the
templates a user is offered. Copies each template icon into figures/icons/
and emits icongrid.tex, which main.tex inputs.

Run from docs/presentations/:
    python3 make_icon_grid.py
"""
import os, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
LIST = os.path.join(REPO, 'resources', 'default_templates.list')
SRC  = os.path.join(REPO, 'resources', 'Icons')
DST  = os.path.join(HERE, 'figures', 'icons')
TEX  = os.path.join(HERE, 'icongrid.tex')

COLUMNS = 8          # templates per row on the slide

# Display names are taken from the list verbatim, with these tidied for the
# slide only (the .list spellings are kept as the source of truth).
RELABEL = {
    "Physics based data driven hydrology": "Physics-based\\\\data-driven\\\\hydrology",
    "CN Catchment (SCS Curve Number)":     "CN catchment\\\\(SCS)",
    "Soil Evapotranspiration models":      "Soil evapo-\\\\transpiration",
    "Evapotranspiration models":           "Evapo-\\\\transpiration",
    "Mixed Hydrologic Response Unit":      "Mixed hydrologic\\\\response unit",
    "Hydrologic Response Unit":            "Hydrologic\\\\response unit",
    "Urban Water Management":              "Urban water\\\\management",
    "Rainfall/runoff modeling":            "Rainfall-runoff",
    "Unconfined Aquifer":                  "Unconfined\\\\aquifer",
    "Reservoir Operation":                 "Reservoir\\\\operation",
    "Wastewater processes":                "Wastewater\\\\processes",
    "Build up-Wash off":                   "Build-up /\\\\wash-off",
    "Pipe/Pump systems":                   "Pipe and pump\\\\systems",
    "River Processes":                     "River\\\\processes",
    "Unsaturated Soil":                    "Unsaturated\\\\soil",
    "Open Channel":                        "Open channel",
    "Sewer System":                        "Sewer system",
    "Mass Transfer":                       "Mass transfer",
}

def read_templates():
    out = []
    for line in open(LIST, encoding='utf-8'):
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(',')]
        if len(parts) != 3:
            raise SystemExit("malformed line in default_templates.list: " + line)
        out.append(tuple(parts))          # (display name, json, icon)
    return out

def main():
    os.makedirs(DST, exist_ok=True)
    temps = read_templates()

    missing = [i for _, _, i in temps if not os.path.exists(os.path.join(SRC, i))]
    if missing:
        raise SystemExit("icons not found in resources/Icons: " + ", ".join(missing))
    for _, _, icon in temps:
        shutil.copy(os.path.join(SRC, icon), os.path.join(DST, icon.replace(' ', '_')))

    out = ["% GENERATED by make_icon_grid.py -- do not edit by hand.",
           "% Source: resources/default_templates.list (the GUI's Add-plugin menu).",
           ""]
    cw = "%.4f" % (1.0 / COLUMNS - 0.004)
    for i in range(0, len(temps), COLUMNS):
        row = temps[i:i + COLUMNS]
        out.append(r"\begin{columns}[T,onlytextwidth]")
        for name, _, icon in row:
            label = RELABEL.get(name, name)
            out.append(r"  \begin{column}{%s\textwidth}\centering" % cw)
            out.append(r"    \includegraphics[height=\iconsize]{icons/%s}\\[2pt]"
                       % icon.replace(' ', '_'))
            out.append(r"    \parbox[t][\iconlabelht][t]{\linewidth}"
                       r"{\centering\tiny %s}" % label)
            out.append(r"  \end{column}")
        # pad a short final row so it stays left-aligned with the others
        for _ in range(COLUMNS - len(row)):
            out.append(r"  \begin{column}{%s\textwidth}\end{column}" % cw)
        out.append(r"\end{columns}")
        out.append(r"\vspace{\iconrowgap}")
    open(TEX, 'w', encoding='utf-8').write("\n".join(out) + "\n")
    print("wrote %s  (%d templates, %d per row)"
          % (os.path.relpath(TEX, HERE), len(temps), COLUMNS))

if __name__ == '__main__':
    main()
