#!/usr/bin/env python3
"""
Emit fig_cumvolume.tex: cumulative volumes, truth against the running twin.

This is the framework's headline claim made visible. Cheap sensors report
depth and moisture; what performance accounting needs is volume. The twin
turns one into the other, and stays on it for two years including through the
imposed clogging.

Sources (OpenHydroTwin/deployments/), matching Plots/plot_paper_cumulative_volume.gp:
  Bioretention_truth_drift_RUN1_outputs/selected_output.csv            (truth)
  Bioretention_assimilation_drift/outputs/selected_output.csv          (twin)

RUN1_outputs is the preserved full-length output of the Bioretention_truth_drift
deployment; its live outputs/ folder was wiped and restarted by a later run and
now covers only the first 140 days.

Flows are m3/day and the save interval is hourly, so volume integrates with a
fixed dt of 1/24 d, as the paper's gnuplot script does.

The published version carries a third "reanalysis" series that sits far above
both and distracts from the comparison that matters; it is left out here.
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
DEP = os.path.join(HERE, '..', '..', '..', 'OpenHydroTwin', 'deployments')
TRUTH = os.path.join(DEP, 'Bioretention_truth_drift_RUN1_outputs', 'selected_output.csv')
TWIN = os.path.join(DEP, 'Bioretention_assimilation_drift',
                    'outputs', 'selected_output.csv')
OUT = os.path.join(HERE, 'fig_cumvolume.tex')

EPOCH = 43831.0
ONSET = 44166.0
CHANNEL = 'Underdrain flow (m3/day)'

def cumulative(path, name):
    rd = csv.reader(open(path))
    hdr = [h.strip() for h in next(rd)]
    idx = {hdr[i + 1]: (i, i + 1) for i in range(0, len(hdr) - 1, 2)}
    ti, vi = idx[name]
    DT = 1.0 / 24.0
    pts, tot = [], 0.0
    for r in rd:
        if len(r) <= vi:
            continue
        try:
            t, v = float(r[ti]), float(r[vi])
        except ValueError:
            continue
        tot += max(v, 0.0) * DT
        pts.append((t - EPOCH, tot))
    return pts

def thin(pts, n=420):
    k = max(1, len(pts) // n)
    out = pts[::k]
    if out[-1] != pts[-1]:
        out.append(pts[-1])
    return out

def coords(pts):
    return " ".join("(%.2f,%.1f)" % p for p in pts)

tr = thin(cumulative(TRUTH, CHANNEL))
tw = thin(cumulative(TWIN, CHANNEL))
xmax = min(tr[-1][0], tw[-1][0])
tr = [p for p in tr if p[0] <= xmax]
tw = [p for p in tw if p[0] <= xmax]
final_err = 100.0 * (tw[-1][1] - tr[-1][1]) / tr[-1][1]

tex = r"""%% GENERATED by make_cumvolume.py -- do not edit by hand.
\documentclass[border=4pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{helvet}
\renewcommand\familydefault{\sfdefault}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}

\definecolor{ohqblue}{HTML}{1F5C8B}
\definecolor{ohqrust}{HTML}{E76F51}
\definecolor{ohqgrey}{HTML}{6B7280}

\begin{document}
\begin{tikzpicture}[font=\sffamily]
\begin{axis}[
  width=15cm, height=7.2cm,
  xmin=0, xmax=__XMAX__, ymin=0, ymax=__YMAX__,
  xlabel={days of operation},
  ylabel={cumulative underdrain volume (m$^3$)},
  label style={font=\small, text=ohqgrey},
  tick label style={font=\small, text=ohqgrey},
  axis line style={ohqgrey!60}, tick style={ohqgrey!60},
  grid=major, major grid style={ohqgrey!15},
  xtick={0,90,180,270,360,450,540,630,720},
  legend style={font=\small, draw=ohqgrey!40, at={(0.03,0.97)},
                anchor=north west, fill=white},
  legend cell align=left,
]
\addplot[ohqgrey, line width=3pt, opacity=0.40] coordinates {__TRUTH__};
\addlegendentry{truth}
\addplot[ohqrust, line width=1.2pt] coordinates {__TWIN__};
\addlegendentry{twin, running live}

\draw[ohqgrey, dashed, line width=0.8pt]
  (axis cs:__ONSET__,0) -- (axis cs:__ONSET__,__YMAX__);
\node[font=\small, text=ohqgrey, anchor=north west, xshift=3pt]
  at (axis cs:__ONSET__,__YMAX__) {clogging begins};
\node[font=\small\bfseries, text=ohqrust, anchor=south east, yshift=3pt]
  at (axis cs:__XMAX__,0) {two years of operation, __ERR__\% apart at the end\ };
\end{axis}
\end{tikzpicture}
\end{document}
"""
ymax = 1000.0 * (int(max(tr[-1][1], tw[-1][1]) / 1000.0) + 1)

for k, v in [('__XMAX__', '%.0f' % xmax), ('__YMAX__', '%.0f' % ymax), ('__ONSET__', '%.0f' % (ONSET - EPOCH)),
             ('__TRUTH__', coords(tr)), ('__TWIN__', coords(tw)),
             ('__ERR__', '%.1f' % abs(final_err))]:
    tex = tex.replace(k, v)
open(OUT, 'w').write(tex)
print("wrote fig_cumvolume.tex: truth %.0f m3, twin %.0f m3, %.2f%% apart"
      % (tr[-1][1], tw[-1][1], final_err))
