#!/usr/bin/env python3
"""
Emit fig_eventzoom.tex: one storm, truth against the twin's forward run.

Sources (OpenHydroTwin/deployments/):
  Bioretention_truth_drift_RUN1_outputs/selected_output.csv           (truth)
  Bioretention_assimilation_drift/outputs/selected_output.csv         (twin)

The published figure spans a whole week, so the storm occupies about a tenth
of the width and the rest is a flat line. This crops to the event.
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
DEP = os.path.join(HERE, '..', '..', '..', 'OpenHydroTwin', 'deployments')
TRUTH = os.path.join(DEP, 'Bioretention_truth_drift_RUN1_outputs', 'selected_output.csv')
TWIN = os.path.join(DEP, 'Bioretention_assimilation_drift',
                    'outputs', 'selected_output.csv')
OUT = os.path.join(HERE, 'fig_eventzoom.tex')

EPOCH = 43831.0            # 2020-01-01
# Use a LATE storm: early in the record the assimilation is still in its
# convergence transient and the twin visibly undershoots the peak. By day ~120
# the parameters have settled, which is the regime the slide is claiming.
T0, T1 = 43950.6, 43953.4  # the 179 mm/day storm on day ~120

def series(path, name):
    rd = csv.reader(open(path))
    hdr = [h.strip() for h in next(rd)]
    idx = {hdr[i + 1]: (i, i + 1) for i in range(0, len(hdr) - 1, 2)}
    ti, vi = idx[name]
    out = []
    for r in rd:
        if len(r) <= vi:
            continue
        try:
            t, v = float(r[ti]), float(r[vi])
        except ValueError:
            continue
        if T0 <= t <= T1:
            out.append((t - EPOCH, v))
    return out

def coords(pts, every=1):
    return " ".join("(%.4f,%.4f)" % p for p in pts[::every])

precip = series(TRUTH, 'Precipitation (mm/day)')
q_true = series(TRUTH, 'Underdrain flow (m3/day)')
q_twin = series(TWIN,  'Underdrain flow (m3/day)')
d_true = series(TRUTH, 'Pond water depth (m)')
d_twin = series(TWIN,  'Pond water depth (m)')

x0, x1 = T0 - EPOCH, T1 - EPOCH

tex = r"""%% GENERATED by make_eventzoom.py -- do not edit by hand.
\documentclass[border=4pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{helvet}
\renewcommand\familydefault{\sfdefault}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}

\definecolor{ohqblue}{HTML}{1F5C8B}
\definecolor{ohqteal}{HTML}{2A9D8F}
\definecolor{ohqrust}{HTML}{E76F51}
\definecolor{ohqgrey}{HTML}{6B7280}

\begin{document}
\begin{tikzpicture}[font=\sffamily]
\pgfplotsset{every axis/.append style={
  width=15cm, xmin=__X0__, xmax=__X1__,
  label style={font=\small, text=ohqgrey},
  tick label style={font=\small, text=ohqgrey},
  axis line style={ohqgrey!60}, tick style={ohqgrey!60},
  grid=major, major grid style={ohqgrey!15},
  xtick={__XTICKS__},
}}

\begin{axis}[name=rain, height=3.5cm,
  ylabel={rain (mm/day)}, ymin=0, ymax=220, ytick={0,100,200},
  xticklabels={}, y dir=reverse, axis x line=top, xticklabel pos=top,
  xticklabels={}]
\addplot[ohqblue, line width=0.9pt, fill=ohqblue!25] coordinates {__PRECIP__} \closedcycle;
\end{axis}

\begin{axis}[name=flow, at={(rain.below south west)}, anchor=north west,
  yshift=-2pt, height=5.0cm,
  ylabel={underdrain flow (m$^3$/day)}, ymin=0, xticklabels={},
  legend style={font=\small, draw=ohqgrey!40, at={(0.98,0.95)},
                anchor=north east, fill=white},
  legend cell align=left]
\addplot[ohqgrey, line width=2.2pt, opacity=0.45] coordinates {__QTRUE__};
\addlegendentry{truth}
\addplot[ohqrust, line width=1.1pt] coordinates {__QTWIN__};
\addlegendentry{twin}
\end{axis}

\begin{axis}[name=depth, at={(flow.below south west)}, anchor=north west,
  yshift=-2pt, height=4.2cm,
  xlabel={day of 2020}, ylabel={pond depth (m)}, ymin=0]
\addplot[ohqgrey, line width=2.2pt, opacity=0.45] coordinates {__DTRUE__};
\addplot[ohqrust, line width=1.1pt] coordinates {__DTWIN__};
\end{axis}

\end{tikzpicture}
\end{document}
"""
import math
ticks = []
tk = math.ceil(x0 * 2) / 2.0
while tk <= x1:
    ticks.append('%.1f' % tk); tk += 0.5

for k, v in [('__X0__', '%.3f' % x0), ('__X1__', '%.3f' % x1),
             ('__XTICKS__', ','.join(ticks)),
             ('__PRECIP__', coords(precip)), ('__QTRUE__', coords(q_true)),
             ('__QTWIN__', coords(q_twin, 2)), ('__DTRUE__', coords(d_true)),
             ('__DTWIN__', coords(d_twin, 2))]:
    tex = tex.replace(k, v)
open(OUT, 'w').write(tex)
print("wrote fig_eventzoom.tex  (precip %d, q_true %d, q_twin %d pts)"
      % (len(precip), len(q_true), len(q_twin)))
