cp /lib/x86_64-linux-gnu/libgomp.so.1 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/libarmadillo.so.9 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/liblapack.so.3 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libblas.so.3 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /home/arash/Qt/5.15.2/gcc_64/lib/libQt5Widgets.so.5 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /home/arash/Qt/5.15.2/gcc_64/lib/libQt5Gui.so.5 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /home/arash/Qt/5.15.2/gcc_64/lib/libQt5Core.so.5 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libGL.so.1 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libpthread.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libstdc++.so.6 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libm.so.6 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libgcc_s.so.1 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libc.so.6 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libdl.so.2 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libarpack.so.2 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libsuperlu.so.5 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libgfortran.so.5 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libz.so.1 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /home/arash/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /home/arash/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /home/arash/Qt/5.15.2/gcc_64/lib/libicudata.so.56 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libgthread-2.0.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libglib-2.0.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libGLdispatch.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libGLX.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libquadmath.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libpcre.so.3 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libX11.so.6 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libxcb.so.1 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libXau.so.6 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libXdmcp.so.6 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
cp /lib/x86_64-linux-gnu/libbsd.so.0 /home/arash/Projects/QAquifolium/bin-console/Release/Package/usr/lib/x86_64-linux-gnu/copied_libs
